name: npm-publish

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

permissions:
  contents: read
  id-token: write

jobs:
  eslint-config:
    runs-on: ubuntu-latest
    environment:
      name: npm
      url: https://www.npmjs.com/package/@amezin/eslint-config-js-actions

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: package.json
          registry-url: https://registry.npmjs.org

      - run: npm --no-git-tag-version version from-git
        working-directory: packages/eslint-config

      - run: npm publish --provenance --access public
        working-directory: packages/eslint-config

  octokit:
    runs-on: ubuntu-latest
    environment:
      name: npm
      url: https://www.npmjs.com/package/@amezin/js-actions-octokit

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: package.json
          registry-url: https://registry.npmjs.org

      - run: npm --no-git-tag-version version from-git
        working-directory: packages/octokit

      - run: npm install
        working-directory: packages/octokit

      - run: npm publish --provenance --access public
        working-directory: packages/octokit
